# Generated by Django 3.2.9 on 2021-11-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_id_token_pk1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='pk1',
            new_name='id',
        ),
    ]
